webtalk_init -webtalk_dir /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-10-23 05:38:13" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "jes456sl8tvrekdfect6hlalu6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.1_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2828.113 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16,494 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1603405872000" -context "sdk\\\\hardware/1603405872000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1603405872000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1603405872000"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1603405872000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.1" -context "sdk\\\\hardware/1603405872000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1603405872000"
webtalk_add_data -client sdk -key Device -value "7z007s" -context "sdk\\\\hardware/1603405872000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1603405872000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1603405872000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1603405872000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1603405872000"
webtalk_add_data -client sdk -key uid -value "1603405975000" -context "sdk\\\\bsp/1603405975000"
webtalk_add_data -client sdk -key hwid -value "1603405872000" -context "sdk\\\\bsp/1603405975000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1603405975000"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\bsp/1603405975000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1603405975000"
webtalk_add_data -client sdk -key uid -value "1603405977000" -context "sdk\\\\application/1603405977000"
webtalk_add_data -client sdk -key hwid -value "1603405872000" -context "sdk\\\\application/1603405977000"
webtalk_add_data -client sdk -key bspid -value "1603405975000" -context "sdk\\\\application/1603405977000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1603405977000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1603405977000"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\application/1603405977000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1603405977000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1603405977000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1603405977000"
webtalk_add_data -client sdk -key projSize -value "858.9140625" -context "sdk\\\\application/1603405977000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1603406293607"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1603406293607"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1603406293607"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1603406293607"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1603406293607"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1603406293607"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1603406293607"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1603406293607"
webtalk_transmit -clientid 1372356416 -regid "" -xml /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
