# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z007sclg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.cache/wt [current_project]
set_property parent.project_path /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:minized:part0:1.2 [current_project]
set_property ip_repo_paths {
  /home/shebalin/work/q-pix/qpix-digital/prototype-project/ip_repo/pstopl_1.0
  /home/shebalin/work/q-pix/qpix-digital/prototype-project/ip_repo/myip_1.0
} [current_project]
set_property ip_output_repo /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -vhdl2008 -library xil_defaultlib {
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixProtoPkg.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/AxiLiteSlaveSimple.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/imp/QpixAsicArray.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixHitsGen.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixDaqNode.vhd
  /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixProtoRegMap.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixDaqCtrl.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/imp/QpixProtoTop.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/imp/QpixUtilTest.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixTestPatGen.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixDummyTxRx.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixComm.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/mem.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/UartRx.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixRegFile.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixDataProc.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixRoute.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/UartTop.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/UtilityPkg.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixDaqHub.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/UartClockGenerator.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixParser.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixPkg.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/QpixAsicTop.vhd
  /home/shebalin/work/q-pix/qpix-digital/firmware/src/UartTx.vhd
}
add_files /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.srcs/constr_1/qpix.xdc
set_property used_in_implementation false [get_files /home/shebalin/work/q-pix/qpix-digital/prototype-project/QpixProto-Minized/QpixProto.srcs/constr_1/qpix.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top QpixProtoTop -part xc7z007sclg225-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef QpixProtoTop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file QpixProtoTop_utilization_synth.rpt -pb QpixProtoTop_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
